name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  opencv_dart: ^1.4.1
  crop_your_image: ^2.0.0
  file_picker: ^8.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
  ml_linalg: ^13.12.6
  intl: ^0.19.0
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
